// <auto-generated />
using System;
using Arooaf.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arooaf.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arooaf.Api.Entities.Personal", b =>
                {
                    b.Property<Guid>("IdPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EstadoValidacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdTramo")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("IdPersonal");

                    b.HasIndex("IdTramo");

                    b.HasIndex("Documento", "IdTramo")
                        .IsUnique();

                    b.ToTable("personal", (string)null);
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Planilla", b =>
                {
                    b.Property<Guid>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CerradaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("text");

                    b.Property<Guid>("IdResponsable")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTramo")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("TimestampLocal")
                        .HasColumnType("bigint");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdTramo", "Fecha")
                        .IsUnique();

                    b.ToTable("planillas", (string)null);
                });

            modelBuilder.Entity("Arooaf.Api.Entities.PlanillaDetalle", b =>
                {
                    b.Property<Guid>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccionMitigacion")
                        .HasColumnType("text");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EsFalsoPositivo")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("FotoBase64")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HoraMitigacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdPersonal")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlanilla")
                        .HasColumnType("uuid");

                    b.Property<double?>("Kilometraje")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Severidad")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPersonal");

                    b.HasIndex("IdPlanilla", "IdPersonal")
                        .IsUnique();

                    b.ToTable("planilla_detalles", (string)null);
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Tramo", b =>
                {
                    b.Property<Guid>("IdTramo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KmFin")
                        .HasColumnType("integer");

                    b.Property<int>("KmInicio")
                        .HasColumnType("integer");

                    b.Property<double>("LatitudFin")
                        .HasColumnType("double precision");

                    b.Property<double>("LatitudInicio")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudFin")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudInicio")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdTramo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tramos_codigo");

                    b.ToTable("tramos", (string)null);
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("usuario_tramo", b =>
                {
                    b.Property<Guid>("id_usuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_tramo")
                        .HasColumnType("uuid");

                    b.HasKey("id_usuario", "id_tramo");

                    b.HasIndex("id_tramo");

                    b.ToTable("usuario_tramo", (string)null);
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Personal", b =>
                {
                    b.HasOne("Arooaf.Api.Entities.Tramo", "Tramo")
                        .WithMany("Personal")
                        .HasForeignKey("IdTramo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tramo");
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Planilla", b =>
                {
                    b.HasOne("Arooaf.Api.Entities.Tramo", "Tramo")
                        .WithMany("Planillas")
                        .HasForeignKey("IdTramo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tramo");
                });

            modelBuilder.Entity("Arooaf.Api.Entities.PlanillaDetalle", b =>
                {
                    b.HasOne("Arooaf.Api.Entities.Personal", "Personal")
                        .WithMany("PlanillaDetalles")
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arooaf.Api.Entities.Planilla", "Planilla")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("usuario_tramo", b =>
                {
                    b.HasOne("Arooaf.Api.Entities.Tramo", null)
                        .WithMany()
                        .HasForeignKey("id_tramo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arooaf.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Personal", b =>
                {
                    b.Navigation("PlanillaDetalles");
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Planilla", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Arooaf.Api.Entities.Tramo", b =>
                {
                    b.Navigation("Personal");

                    b.Navigation("Planillas");
                });
#pragma warning restore 612, 618
        }
    }
}
